### ISSUE TITLE
Move all datasets to a new raw folder

### ISSUE THREAD

**Issue by LinguList** [martino-vic/streitberggothic#1]
Instructions can be found also specifically here: https://calc.hypotheses.org/2954

This explains the structure you need to convert data to CLDF. Note that conversion is done programmatically, transparently, not by having a dataset in converted form, but by using code to convert spreadsheet data to cldf.

**Comment by LinguList** [comment]
If you provide me write access, I can help more concretely. But the first step is to move data here to raw, leave one file with metadata.json, as shown in the blog post, and also the setup.py file, and having `languages.tsv` and `concepts.tsv` in the folder `etc`.

**Comment by martino-vic** [comment]
closing this since #2 was closed too
