### ISSUE TITLE
orthography

### ISSUE THREAD

**Issue by martino-vic** [martino-vic/streitberggothic#3]
#2 

The current transcription with orthography.tsv is very good, but there are some mistakes that I don't see how to overcome without a rulebased transcriber, e.g.:

- line 1243 is the only non-BIPA conform line, since in `gagáhaftjan > ^ g agá h a f t j a n $ > g a ɣ á h a ɸ t j a n` the rule `á > a` never gets applied. 
- in line 10 `abrs > a β r s` doesn't mark the syllabic <r̥> since the r gets clustered to \<abr\>, so the rule for \<brs\> doesn't apply.

Not only do these rules cancel each other out but also if I wanted to explicitly mention all these transformations in orthography.tsv, i.e. to hardcode every word (which I tried) then the clts-validation is failing since 1 word = 1 grapheme.

I think it would be nice if I could somehow plug in a third-party transcriber and check those results for clts-conformity. I've added the column IPA in a post-processing step for now. Those are generated with the epitran-library and I've included the transcription rules in the folder `etc` for more transparency. I like those transcriptions more, but of course that's not worth much if it can't be checked against the clts data.

**Comment by LinguList** [comment]
Our procedure so far is to say: if there's a case that is applied less than 100 times, we can also spell it out. Why not write the whole word to your profile in Grapheme and then in IPA the segmented one?

**Comment by LinguList** [comment]
People give too much power to rules. It may seem comforting to have a rule that solves a case that occurs five times in your data, but our approach is: if it is not essential for the theory, but to curate the data, it is better to be explicit and add some extra lines, rather than break one's head over finding a way to make a very complex approach to change these five cases to something else. We think this gains transparency ACROSS datasets.

**Comment by martino-vic** [comment]
Thanks for the explanation, seems I forgot to look at the big picture, but now it's clear.

> Why not write the whole word to your profile in Grapheme and then in IPA the segmented one

I don't know why I haven't thought about this. Tried it out and it worked.
