### ISSUE TITLE
Remove Private Files

### ISSUE THREAD

**Issue by LinguList** [martino-vic/streitberggothic#4]
* files ending in *.bat
* files like cmd.txt

They also reveal your local desktop structure, which I consider a bit private ;)

**Comment by LinguList** [comment]
If epitran is no longer used, I'd move the files either to `raw` or remove them.

**Comment by LinguList** [comment]
* makeconcepts.py should be placed into `raw`.

**Comment by LinguList** [comment]
* also, we want to have only languages.tsv, concepts.tsv, and orthography.tsv in the end, if you want to keep the other files, move them to raw (access via `Dataset().raw_dir` as a Python.Path object with a `read_csv` method as well).

**Comment by martino-vic** [comment]
Thank you for the feedback, I'm working on it now 👍

**Comment by martino-vic** [comment]
implemented suggested changes, so closing this
