### ISSUE TITLE
inspect data through edictor

### ISSUE THREAD

**Issue by LinguList** [martino-vic/streitberggothic#5]
@martino-vic, if you want to inspect the data through edictor, I recommend `pyedictor` (pip install pyedictor). 

```
$ edictor wordlist --name streitberggothic
```

A tutorial on the library is pending (maybe next month as blog post). This will convert the data to the TSV you need for lingpy / edictor. Edictor is here: https://lingulist.de/edev/ (dev version), official version: https://digling.org/edictor . May be interesting to check the data in this form. I can explain another time how.

**Comment by LinguList** [comment]
Yes, works nicely. If you load into edictor, you can add columns MORPHEMES and COGIDS and then even do morphological analysis, works like a charm. If we coordinate, you write your blog post to announce the data, and I can write a follow up showing how it can be explored with the most recent EDICTOR version...

**Comment by LinguList** [comment]
![Bildschirmfoto_2022-01-14_08-39-28](https://user-images.githubusercontent.com/2916210/149469606-33b74519-801a-4ff3-a24f-ca595067cc8e.png)

**Comment by martino-vic** [comment]
Sorry for the late reply! This looks really neat, I'm going to play around with it a little bit to explore its funcionality, thanks! Yes,  it would be of course great if we could coordinate it that way :) I wrote a first draft for the blogpost already (only minor changes needed to reflect the changes done in #4 and #6).  

I was wondering if it would make sense to make a short Youtube tutorial accompanying the blogpost? What would you think?

**Comment by martino-vic** [comment]
Okay so I followed step 8 of the tutorial for Vietic and it was actually clear enough to use pyedictor. Worked out on the first try :)
![Screenshot (3)](https://user-images.githubusercontent.com/53435298/149639231-65619bc7-df99-4e45-b3e2-ea87cf94e604.png)

**Comment by LinguList** [comment]
A youtube tutorial would be excellent.

**Comment by LinguList** [comment]
As to concepticon glosses instead of the original senses: for mono-lingual work, you prefer the German ones, of course, or English glosses, which you'd have to provide. For comparative work across several languages, where you merge varieties, you'd want to have concepticon. But here, you'd also miss many entries that have not been mapped, etc.

**Comment by martino-vic** [comment]
So this would be the Youtube thing, the blogpost still needs some editing but should be ready tomorrow
https://www.youtube.com/watch?v=zgLrDJ0zMPQ

**Comment by LinguList** [comment]
Nice, I'd suggest to make the title the same as the blog (à la 
"Converting Streitberg's Gothic Dictionary to a CLDF Wordlist"). I'll 
send you an invitation with username for our blog, afterwards, we have 
to coordinate, it would be published in February. We discuss this via 
email. One step, but maybe enough for one more blog post, would be to 
also make a CLDF Dictionary (which is form-based, with senses instead of 
concepts), but this is definitely a second step, I'd say.

**Comment by martino-vic** [comment]
Renamed the video, received the invitation, and yes, would be exciting to learn how to convert to other data formats as well! Will reply to the e-mails today. And am closing this since further discussion is via e-mail
