### ISSUE TITLE
Transfer to Lexibank or Submit to Zenodo

### ISSUE THREAD

**Issue by LinguList** [martino-vic/streitberggothic#7]
We have two possibilities to publish the repo with Zenodo:

1. transfer to the lexibank organization on Zenodo, we will take care of publication then (authorship etc. won't change, of course)
2. submit directly to zenodo, using Zendodo's possibility to submit repositories along with a new release. This means you have to follow zenodo's guideline and set this up yourself, and we make a release then, so it will be automatically linked on Zenodo.

**Comment by martino-vic** [comment]
Cool! So I chose option two, made a release and submitted it to Zenodo: [![DOI](https://zenodo.org/badge/444373577.svg)](https://zenodo.org/badge/latestdoi/444373577). Is there anything left to do for me?

**Comment by LinguList** [comment]
Yes, please add the repository to the lexibank community. From there, we accept it then, and it is then part of lexibank.

**Comment by martino-vic** [comment]
Okay so on Zenodo, I edited the record, added the lexibank community under the "Communities" section, saved, and published. So in theory, the community curator should get a notification now

**Comment by martino-vic** [comment]
Beyond excited that the transfer worked out and grateful for the good cooperation!
